#!/usr/bin/env bash

# The Comment

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 470877-web-01 54.172.83.174:80 check
    server 470877-web-02 54.236.54.173:80 check
"
apt-get -y update
apt-get -y upgrade

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
