#!/usr/bin/env bash
# ggggggggggggggggg
# ggggggggggggggggg
# ggggggggggggggggg
# ggggggggggggggggg
# ggggggggggggggggg
# ggggggggggggggggg


while true
do
  echo "To infinity and beyond"
  sleep 2
done

