#!/usr/bin/env bash
# jjjjjjjjjjjjjjjjjjjjjjjjj
# jjjjjjjjjjjjjjjjjjjjjjjjj
# jjjjjjjjjjjjjjjjjjjjjjjjj
# jjjjjjjjjjjjjjjjjjjjjjjjj
# jjjjjjjjjjjjjjjjjjjjjjjjj
# jjjjjjjjjjjjjjjjjjjjjjjjj

kill "$(pgrep -f 4-to_infinity_and_beyond)"

