#!/usr/bin/env bash
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff
# ffffffffffffffffffffffffff

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
